# Site settings
title: Rune Madsen - Multimedia Artist
name: Rune Madsen
email: rune@runemadsen.com
description: "Rune Madsen is a Danish designer, programmer, artist and educator living in New York City."
keywords: "algorithmic graphic design, generative design, rune madsen, Processing, creative code"
twitter_username: runemadsen
github_username:  runemadsen
url: "https://www.runemadsen.com"
highlighter: pygments
permalink: /:categories/:title/
exclude: [Gemfile, Gemfile.lock]
excerpt_separator: ""
paginate: 5
gems:
  - jekyll-sitemap
  - jekyll-paginate
assets:
  digest: true
  sources:
    - _assets/javascripts
    - _assets/stylesheets
    - _assets/images
    - _assets/fonts
